name: Main Workflow

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push_docker_image:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD_hh-mm-ss' tz='America/Sao_Paulo'}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PORT=${{ vars.PORT }}
            HOST=${{ vars.HOST }}
            WS_PATH=${{ vars.WS_PATH }}
            ROOM_CAPACITY=${{ vars.ROOM_CAPACITY }}
            TICK_HZ=${{ vars.TICK_HZ }}
            MAX_ROOMS=${{ vars.MAX_ROOMS }}
            MAX_CONNECTIONS=${{ vars.MAX_CONNECTIONS }}
